name: Deploy to GitHub pages

# Run workflow on every push to the master branch
on: [push]

jobs:
  deploy-to-github-pages:
    # Use Ubuntu-latest image to run steps on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - run: dotnet workload install wasm-tools          
      - run: dotnet publish SDXImageWeb.csproj -c Release -o release
      - run: sed -i 's/<base href="\/" \/>/<base href="\/SDXImageWeb\/" \/>/g' release/wwwroot/index.html
      - run: cp release/wwwroot/index.html release/wwwroot/404.html
      - run: touch release/wwwroot/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
